### ISSUE TITLE
ld and st instruction buggy

### ISSUE THREAD

**Issue by MilosSubotic** [filiparag/ftn-lprsemu#3]
By specification:
ld Rz,Ry	RZ ← [[RY]]
st Rx,Ry	[[RY]] ← [RX]
and order of instruction fields should is
OPCODE Rz Rx Ry.

But it seems that this assembler generates:
ld Rz,Rx
i.e. second operand register is stored to Rx instead of Ry field.

For st instruction assembler generates 
OPCODE Rx Ry Rz.

**Comment by filiparag** [comment]
To clarify, is this the correct generation:

```rust
const EMPTY_REG: u8 = 0;

impl ToVhdl for MemoryInstruction {
    fn to_vhdl(&self) -> String {
        match *self {
            Self::Load(rz, ry) => format!("100000{}", encode_registers(rz, EMPTY_REG, ry)),
            Self::Store(rx, ry) => format!("110000{}", encode_registers(rx, ry, EMPTY_REG)),
        }
    }
}
```

For `ld Rz, Ry` generate `OPCODE Rz EMPTY_REG Ry`.
For `st Rx, Ry` generate `OPCODE Rx Ry EMPTY_REG`.

**Comment by TeoNov** [comment]
Load is ok, but store is not ok. It should be:

For ld Rz, Ry generate OPCODE Rz EMPTY_REG Ry.
For st Rx, Ry generate OPCODE EMPTY_REG Rx Ry.
